- name: Test whether Sysmon executable is present
  win_stat:
    path: "{{ executable_path }}"
  register: sysmon_executable

- name: Download Sysmon
  win_get_url:
    url: https://live.sysinternals.com/Sysmon64.exe
    dest: "{{ executable_path }}"
  when: not sysmon_executable.stat.exists

- name: Install Sysmon
  win_command: "{{ executable_path }} -i -accepteula -n"
  when: not sysmon_executable.stat.exists