- name: Ensure Network Service is part of the Event Logs Readers local group
  win_group_membership:
    name: Event Log Readers
    members: Network Service

- name: Enable process tracking # todo: Is this considered best practice or not?
  win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\Audit
    name: ProcessCreationIncludeCmdLine_Enabled
    value: 1

- name: Allow Network Service to read "Security" and "Microsoft-Windows-Sysmon/Operational" Event Logs (only relevant for domain controllers)
  win_command: powershell.exe -
  args:
    stdin: >
      wevtutil sl {{ item }} /ca:'O:BAG:SYD:(A;;0xf0005;;;SY)(A;;0x5;;;BA)(A;;0x1;;;S-1-5-32-573)(A;;0x1;;;S-1-5-20)'
  with_items:
    - Security 
    - Microsoft-Windows-Sysmon/Operational