---
- name: Configure domain controllers
  hosts: domain_controllers
  gather_facts: no
  roles:
  - role: domain-controller
  - role: windows-base
  - role: wef-client
  - role: sysmon
    tags: [ sysmon ]
  - role: logging-base
    tags: [ logging-base ]
  - role: server-audit-policy
    tags: [ audit-policy ]
  - role: domain-controller-audit-policy
    tags: [ audit-policy ]