---
- name: Configure workstations
  hosts: workstations
  gather_facts: no
  roles:
  - role: domain-member
  - role: windows-base
  - role: wef-client
  - role: sysmon
  - role: logging-base
  - role: workstation-audit-policy
  - role: wireshark